const routeLoaders = {
  NotFound: () => import('../pages/NotFound'),
  Login: () => import('../pages/auth/Login'),
  ChangePassword: () => import('../pages/auth/ChangePassword'),
  Dashboard: () => import('../pages/home/Dashboard'),
  CreateInvoice: () => import('../pages/invoice/CreateInvoice'),
  InvoiceOverview: () => import('../pages/invoice/InvoiceOverview'),
  EditInvoice: () => import('../pages/invoice/EditInvoice'),
  ViewInvoice: () => import('../pages/invoice/ViewInvoice'),
  CreateJournal: () => import('../pages/journal/CreateJournal'),
  JournalOverview: () => import('../pages/journal/JournalOverview'),
  EditJournal: () => import('../pages/journal/EditJournal'),
  ViewJournal: () => import('../pages/journal/ViewJournal'),
  RateOverview: () => import('../pages/rates/RateOverview'),
  CreateRate: () => import('../pages/rates/CreateRate'),
  EditRate: () => import('../pages/rates/EditRate'),
  ClientOverview: () => import('../pages/clients/ClientOverview'),
  CreateClient: () => import('../pages/clients/CreateClient'),
  EditClient: () => import('../pages/clients/EditClient'),
  ViewClient: () => import('../pages/clients/ViewClient'),
  ProjectOverview: () => import('../pages/projects/ProjectOverview'),
  CreateProject: () => import('../pages/projects/CreateProject'),
  EditProject: () => import('../pages/projects/EditProject'),
  ViewProject: () => import('../pages/projects/ViewProject'),
  AccountOverview: () => import('../pages/account/AccountOverview'),
  CreateAccount: () => import('../pages/account/CreateAccount'),
  EditAccount: () => import('../pages/account/EditAccount'),
  ViewAccount: () => import('../pages/account/ViewAccount'),
  BankOverview: () => import('../pages/banks/BankOverview'),
  CreateBank: () => import('../pages/banks/CreateBank'),
  EditBank: () => import('../pages/banks/EditBank'),
  ViewBank: () => import('../pages/banks/ViewBank'),
  LedgerOverview: () => import('../pages/ledger/LegderOverview'),
  CreateLedger: () => import('../pages/ledger/CreateLedger'),
  EditLedger: () => import('../pages/ledger/EditLedger'),
  ViewLedger: () => import('../pages/ledger/ViewLedger'),
  StaffOverview: () => import('../pages/staff/StaffOverview'),
  CreateStaff: () => import('../pages/staff/CreateStaff'),
  EditStaff: () => import('../pages/staff/EditStaff'),
  ViewStaff: () => import('../pages/staff/ViewStaff'),
  TimesheetOverview: () => import('../pages/timesheet/TimesheetOverview'),
  CreateTimesheet: () => import('../pages/timesheet/CreateTimesheet'),
  EditTimesheet: () => import('../pages/timesheet/EditTimesheet'),
  ViewTimesheet: () => import('../pages/timesheet/ViewTimesheet'),
  LedgerReports: () => import('../pages/reports/LedgerReports'),
  LedgerStatement: () => import('../pages/reports/LedgerStatment'),
  GeneralLedger: () => import('../pages/reports/GeneralLedger'),
  TrialBalance: () => import('../pages/reports/TrialBalance'),
  ProfitLoss: () => import('../pages/reports/ProfitLoss'),
  BalanceSheet: () => import('../pages/reports/BalanceSheet'),
  FXRevaluation: () => import('../pages/reports/FXRevaluation'),
  InvoiceAging: () => import('../pages/reports/InvoiceAging'),
  TimesheetReport: () => import('../pages/reports/TimesheetReport'),
  BankReconOverview: () => import('../pages/reports/recon/BankReconOverview'),
  EditBankRecon: () => import('../pages/reports/recon/EditBankRecon'),
  CreateBankRecon: () => import('../pages/reports/recon/CreateBankRecon'),
  BankReconWorkspace: () => import('../pages/reports/recon/BankReconWorkspace'),
  LockPeriodOverview: () => import('../pages/accounting-period/LockPeriodOverview'),
  UsersOverview: () => import('../pages/users/UsersOverview'),
  CreateUser: () => import('../pages/users/CreateUser'),
  EditUser: () => import('../pages/users/EditUser'),
  ViewUser: () => import('../pages/users/ViewUser'),
  MyProfile: () => import('../pages/users/MyProfile'),
  NotificationsPage: () => import('../pages/notifications/NotificationsPage'),
  ActivityLogsPage: () => import('../pages/activity-logs/ActivityLogsPage'),
};

const routeMatchers = [
  [/^\/$/, 'Dashboard'],
  [/^\/login\/?$/, 'Login'],
  [/^\/change-password\/?$/, 'ChangePassword'],
  [/^\/invoice\/home\/?$/, 'InvoiceOverview'],
  [/^\/invoice\/create\/?$/, 'CreateInvoice'],
  [/^\/invoice\/edit\/[^/]+\/?$/, 'EditInvoice'],
  [/^\/invoice\/view\/[^/]+\/?$/, 'ViewInvoice'],
  [/^\/journal\/home\/?$/, 'JournalOverview'],
  [/^\/journal\/create\/?$/, 'CreateJournal'],
  [/^\/journal\/edit\/[^/]+\/?$/, 'EditJournal'],
  [/^\/journal\/view\/[^/]+\/?$/, 'ViewJournal'],
  [/^\/rate\/home\/?$/, 'RateOverview'],
  [/^\/rate\/create\/?$/, 'CreateRate'],
  [/^\/rate\/edit\/[^/]+\/?$/, 'EditRate'],
  [/^\/client\/home\/?$/, 'ClientOverview'],
  [/^\/client\/create\/?$/, 'CreateClient'],
  [/^\/client\/edit\/[^/]+\/?$/, 'EditClient'],
  [/^\/client\/view\/[^/]+\/?$/, 'ViewClient'],
  [/^\/project\/home\/?$/, 'ProjectOverview'],
  [/^\/project\/create\/?$/, 'CreateProject'],
  [/^\/project\/edit\/[^/]+\/?$/, 'EditProject'],
  [/^\/project\/view\/[^/]+\/?$/, 'ViewProject'],
  [/^\/banks\/home\/?$/, 'BankOverview'],
  [/^\/banks\/create\/?$/, 'CreateBank'],
  [/^\/banks\/edit\/[^/]+\/?$/, 'EditBank'],
  [/^\/banks\/view\/[^/]+\/?$/, 'ViewBank'],
  [/^\/account\/home\/?$/, 'AccountOverview'],
  [/^\/account\/create\/?$/, 'CreateAccount'],
  [/^\/account\/edit\/[^/]+\/?$/, 'EditAccount'],
  [/^\/account\/view\/[^/]+\/?$/, 'ViewAccount'],
  [/^\/ledger\/home\/?$/, 'LedgerOverview'],
  [/^\/ledger\/create\/?$/, 'CreateLedger'],
  [/^\/ledger\/edit\/[^/]+\/?$/, 'EditLedger'],
  [/^\/ledger\/view\/[^/]+\/?$/, 'ViewLedger'],
  [/^\/staff\/home\/?$/, 'StaffOverview'],
  [/^\/staff\/create-staff\/?$/, 'CreateStaff'],
  [/^\/staff\/edit\/[^/]+\/?$/, 'EditStaff'],
  [/^\/staff\/view\/[^/]+\/?$/, 'ViewStaff'],
  [/^\/timesheet\/home\/?$/, 'TimesheetOverview'],
  [/^\/timesheet\/create-timesheet\/?$/, 'CreateTimesheet'],
  [/^\/timesheet\/edit\/[^/]+\/?$/, 'EditTimesheet'],
  [/^\/timesheet\/view\/[^/]+\/?$/, 'ViewTimesheet'],
  [/^\/reports\/ledger\/?$/, 'LedgerReports'],
  [/^\/reports\/ledger\/ledger-statement\/?$/, 'LedgerStatement'],
  [/^\/reports\/ledger\/general-ledger\/?$/, 'GeneralLedger'],
  [/^\/reports\/ledger\/trial-balance\/?$/, 'TrialBalance'],
  [/^\/reports\/ledger\/profit-and-loss\/?$/, 'ProfitLoss'],
  [/^\/reports\/ledger\/balance-sheet\/?$/, 'BalanceSheet'],
  [/^\/reports\/fx-revaluation\/?$/, 'FXRevaluation'],
  [/^\/reports\/invoice-aging\/?$/, 'InvoiceAging'],
  [/^\/reports\/timesheet\/?$/, 'TimesheetReport'],
  [/^\/reports\/bank-recon\/?$/, 'BankReconOverview'],
  [/^\/reports\/bank-recon\/create\/?$/, 'CreateBankRecon'],
  [/^\/reports\/bank-recon\/edit\/[^/]+\/?$/, 'EditBankRecon'],
  [/^\/reports\/bank-recon\/workspace\/[^/]+\/?$/, 'BankReconWorkspace'],
  [/^\/lock-period\/home\/?$/, 'LockPeriodOverview'],
  [/^\/users\/home\/?$/, 'UsersOverview'],
  [/^\/users\/create-user\/?$/, 'CreateUser'],
  [/^\/users\/edit\/[^/]+\/?$/, 'EditUser'],
  [/^\/users\/view\/[^/]+\/?$/, 'ViewUser'],
  [/^\/users\/my-profile\/?$/, 'MyProfile'],
  [/^\/notifications\/?$/, 'NotificationsPage'],
  [/^\/activity-logs\/?$/, 'ActivityLogsPage'],
];

const loadedRoutes = new Set();

export const preloadRoute = (pathname) => {
  const normalizedPath = String(pathname || '/').split('?')[0].split('#')[0] || '/';
  const match = routeMatchers.find(([pattern]) => pattern.test(normalizedPath));
  const routeName = match?.[1];

  if (!routeName || loadedRoutes.has(routeName)) return Promise.resolve();

  loadedRoutes.add(routeName);
  return routeLoaders[routeName]().catch((error) => {
    loadedRoutes.delete(routeName);
    if (import.meta.env.DEV) console.warn(`Unable to preload route: ${normalizedPath}`, error);
  });
};

export const preloadRoutes = (paths = []) => Promise.allSettled(paths.map(preloadRoute));

export default routeLoaders;
